name: Output Event details
on: issues
jobs:
    output-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print details
              run: echo "${{fromJson(github.event.issue)}}"
        